language: python
dist: trusty
cache:
  pip: true
#  directories:
#    - $HOME/.cache/samples
python:
  - "3.6"
install:
  - git clone --recursive --branch v3.10.0 https://github.com/VirusTotal/yara-python yara-python
  - cd yara-python
  - CFLAGS="-std=gnu99" python setup.py build --enable-dex install
  - cd ../
  - pip install --upgrade pip
  - pip install -e .[dev,test]
  - pip install --upgrade pytest factory_boy
script:
  - ./prep-release.py | true
  - python -m pytest -s
